#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
. "$script_dir/lib.sh"

write_rabbit_hole_check_request \
  "$FORGE_INPUT_REQUEST" \
  "$FORGE_INPUT_REVIEW_CONSENSUS_REQUEST" \
  "$FORGE_INPUT_ROUND_POLICY" \
  "$FORGE_INPUT_ACCEPTED_ROUND_ITERATION_STATUS" \
  "$FORGE_INPUT_ACCEPTED_REVIEW_FINDINGS" \
  "$FORGE_INPUT_REVIEW_AUDIT_RESULT" \
  "$FORGE_INPUT_IMPLEMENTATION_REPORT" \
  "$FORGE_INPUT_EVIDENCE" \
  "$FORGE_INPUT_JUDGE_RESULT" \
  "$FORGE_INPUT_CHECKPOINT_RECORD" \
  > "$FORGE_OUTPUT_RABBIT_HOLE_CHECK_REQUEST"
